imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    esi: { enabled: true }
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments: { path: /_fragment }
    translator: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
    assets:
        jquery_and_bootstrap:
            inputs:
                - '@WoojinBackendBundle/Resources/public/js/jquery.min.js'
                - '@WoojinBackendBundle/Resources/public/js/bootstrap.min.js'
        angular_and_depend:
            inputs:
                - '@WoojinBackendBundle/Resources/public/js/angular/angular.js'
                - '@WoojinBackendBundle/Resources/public/js/angular/angular-route.js'
                - '@WoojinBackendBundle/Resources/public/js/angular/angular-resource.js'
                - '@WoojinBackendBundle/Resources/public/js/angular/angular-animate.js'
                - '@WoojinBackendBundle/Resources/public/js/angular/angular-sanitize.js'
        plugin:
            inputs:
                - '@WoojinBackendBundle/Resources/public/js/plugin/datetimepicker/js/bootstrap-datepicker.js'
                - '@WoojinBackendBundle/Resources/public/js/plugin/datetimepicker/js/locales/bootstrap-datepicker.zh-TW.js'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/bower_components/angular-block-ui/angular-block-ui.min.js'
                - '@WoojinBackendBundle/Resources/public/js/plugin/bower_components/ng-file-upload/angular-file-upload-shim.min.js'
                - '@WoojinBackendBundle/Resources/public/js/plugin/bower_components/ng-file-upload/angular-file-upload.min.js'
                - '@WoojinBackendBundle/Resources/public/js/plugin/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js'
        my_angular:
            inputs:
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/app.js'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/directives.js'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/services.js'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/controller/*'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/controller/Activity/*'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/controller/Backend/*'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/controller/Brand/*'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/controller/Color/*'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/controller/Custom/*'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/controller/GoodsLevel/*'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/controller/GoodsMt/*'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/controller/GoodsPassport/*'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/controller/Move/*'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/controller/Orders/*'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/controller/Pattern/*'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/controller/PayType/*'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/controller/GoodsPassport/*'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/controller/Supplier/*'
                - '@WoojinBackendBundle/Resources/public/js/angular-seed/app/js/controller/User/*'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

nelmio_api_doc: ~

services:  
    goods.importer.mapping.setter:
        class: Woojin\GoodsBundle\Importer\Setter\MappingSetter

    entity.pro.getter:
        class: Woojin\Entity\ProGetter

    goods.setter:
        class: Woojin\GoodsBundle\GoodsSetter

    goods.exporter:
        class: Woojin\GoodsBundle\GoodsExporter
        arguments: ['@service_container', '@security.context']

    goods.importer:
        class: Woojin\GoodsBundle\Importer\GoodsImporter
        arguments: ['@doctrine', '@service_container', '@security.context']

    custom.factory:
        class: Woojin\OrderBundle\CustomFactory
        arguments: ['@doctrine', '@security.context']

    ope.factory:
        class: Woojin\OrderBundle\OpeFactory
        arguments: ['@doctrine', '@security.context']

    order.factory:
        class: Woojin\OrderBundle\OrderFactory
        arguments: ['@doctrine', '@security.context']

    goods.factory:
        class: Woojin\GoodsBundle\GoodsFactory
        arguments: ['@doctrine', '@security.context']

    user_service:
        class: Woojin\UserBundle\WoojinUserBundle

    invoice.formatter:
        class: Woojin\OrderBundle\InvoiceFormatter

    goods.subscriber:
        class: Woojin\GoodsBundle\EventListener\GoodsSubscriber
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber}

    order.subscriber:
        class: Woojin\OrderBundle\EventListener\OrderSubscriber
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber}
