woojin_api:
    resource: "@WoojinApiBundle/Controller/"
    type:     annotation
    prefix:   /api/v1

woojin_backend:
    resource: "@WoojinBackendBundle/Controller/"
    type:     annotation
    prefix:   /backend

woojin_user:
    resource: "@WoojinUserBundle/Controller/"
    type:     annotation
    prefix:   /user

woojin_login:
    resource: "@WoojinSecurityBundle/Controller/SecurityController.php"
    type:     annotation

woojin_goods:
    resource: "@WoojinGoodsBundle/Controller/"
    type:     annotation

woojin_store:
    resource: "@WoojinStoreBundle/Controller/"
    type:     annotation

woojin_order:  
    resource: "@WoojinOrderBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
